trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'vs2017-win2016'

    variables:
      sonarCloudNameToken: 'Service connection Sonar Cloud'
      sonarCloudOrganization: 'camilomr'
      sonarCloudProjectKey: 'PetBook'
      sonarCloudProjectName: 'PetBook'

    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: '$(sonarCloudNameToken)'
        organization: '$(sonarCloudOrganization)'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '$(sonarCloudProjectKey)'
        cliProjectName: '$(sonarCloudProjectName)'
        cliSources: '.'
        
    - task: Npm@1
      inputs:
        command: 'install'
      
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
      
    - task: SonarCloudAnalyze@1
    
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run test-ci'